version: 2
jobs:
  build:
    docker:
      - image: swift:4.1.3
    steps:
      - checkout

      - run:
          name: Show swift version
          command: swift --version

      - run:
          name: Build artifacts
          command: swift build

      - run:
          name: Run tests
          command: swift test > test-report.txt 2>&1

      - run:
          name: Show results
          command: cat test-report.txt

      - store_test_results:
          path: test-report.txt
